### ISSUE TITLE
Include requirements.txt

### ISSUE THREAD

**Issue by cjrollo** [ProtosaurusRex/People-and-Notes#2]
manually installed a bunch of modules.

>  pip install flask
>  pip install Marshmallow
>  pip install SQLAlchemy
>  pip install flask_marshmallow
>  pip install connexion
>  pip install flask_sqlalchemy
>  pip install connexion[flask]
>  pip install marshmallow_sqlalchemy

>  pip install connexion[uvicorn]
>  pip install connexion[swagger-ui]

**Comment by ProtosaurusRex** [comment]
An updated requirements file has been added to the repo. Run using 'pip install -r requirements'  within the virtual enviornment.
